### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by sev7ennaiyou** [Schaka/LoseControl#4]
I download its called lose control master, and PeaZip in my interface and addon its didn't show in my game interface list......

**Comment by sev7ennaiyou** [comment]
a lot of interface error 
![wowscrnshot_060917_232426](https://user-images.githubusercontent.com/29320935/26999229-b9d0de0a-4d6a-11e7-9c3b-0e33bb4dd189.jpg)
![wowscrnshot_060917_232433](https://user-images.githubusercontent.com/29320935/26999230-b9d0f03e-4d6a-11e7-8368-f2109bfb2aac.jpg)
![wowscrnshot_060917_232458](https://user-images.githubusercontent.com/29320935/26999231-b9d60d80-4d6a-11e7-9160-c85eb8743171.jpg)
![wowscrnshot_060917_232505](https://user-images.githubusercontent.com/29320935/26999232-b9d6c680-4d6a-11e7-9c17-867e165788cf.jpg)

**Comment by Schaka** [comment]
Just ignore Lua errors. It has no effect on how the actual addon works. I might get around to fixing it eventually.

**Comment by sev7ennaiyou** [comment]
Thank for replying, and I can't not change the target frame when they are
sheepped or feared, the target frame will change to like this,

 I tried many addons and still not working hope the loss control will help
I will w8 for the update vision and try again
thank you very much

**Comment by Schaka** [comment]
Hey,

it might be an issue with you using the Chinese client. You should try using an English client.

But for now, you can try the following:

- Log out of the game.
- Go to your WoW folder -> WTF -> AccountName -> AccountName -> SavedVariables, and delete LoseControl.lua and LoseControl,lua.bak.
- download LoseControl here as a zip file
- take the folder inside called "LoseControl-master" and rename to "LoseControl"
- copy that folder into Interface\AddOns

If this doesn't work, it's safe to assume your problem is with the Chinese client you're using and I highly recommend not doing that.

**Comment by sev7ennaiyou** [comment]
holy shit, it works
 I use English client but with Chinese front, but somehow it works
thank you very much !!!!!
